server:
  port: 8088

auth:
  jwt:
    resourceId: "release-coordinator"
    publicKeyUrl: "https://ego-qa.kids-first.io/oauth/token/public_key"

release-coordinator:
  url: https://kf-release-coord-qa.kidsfirstdrc.org
  # used to make secure REST calls to release coordinator
  auth:
    enable: false

rollcall:
  url: http://localhost:8080
  # used to make secure REST calls to rollcall
  auth:
    enable: true

docker:
  image:
    useLocal: true
  # This can be a tag (if useLocal == false) or an imageId (if useLocal == true)
    id: <docker images | head -2 | tail -1>
  network:
    id: default
  input:
    conf: <path to kf_etl.conf file>
